apiVersion: v1
kind: Service
metadata:
  labels:
    app: lectern-dev
  name: lectern-dev-svc
  namespace: pdcm-validator-dev
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
    nodePort: 32001
  selector:
    app: lectern-dev
  type: NodePort
status:
  loadBalancer: {}