apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongo-db
  name: mongo-db-svc
  namespace: pdcm-validator
spec:
  ports:
  - port: 27017
    protocol: TCP
    targetPort: 27017
    nodePort: 32726
  selector:
    app: mongo-db
  type: NodePort
status:
  loadBalancer: {}