apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-db-pvc
  labels:
    app: lectern
  namespace: pdcm-validator
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: standard-nfs-production
