apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongo-db-dev
  name: mongo-db-dev-svc
  namespace: pdcm-validator-dev
spec:
  ports:
  - port: 27017
    protocol: TCP
    targetPort: 27017
    nodePort: 32000
  selector:
    app: mongo-db-dev
  type: NodePort
status:
  loadBalancer: {}