apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-db-dev-pvc
  labels:
    app: lectern-dev-dev
  namespace: pdcm-validator-dev
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: standard-nfs-production
