apiVersion: v1
kind: Service
metadata:
  labels:
    app: lectern
  name: lectern-svc
  namespace: pdcm-validator
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
    nodePort: 30200
  selector:
    app: lectern
  type: NodePort
status:
  loadBalancer: {}