apiVersion: apps/v1
kind: Deployment
metadata:
  name: pdcm-lectern-validator
  namespace: pdcm-validator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pdcm-lectern-validator
  template:
    metadata:
      labels:
        app: pdcm-lectern-validator
    spec:
      containers:
      - name: pdcm-lectern-validator
        image: pdxfinder/pdcm-lectern-validator:dev
        imagePullPolicy: Always
        env:
        - name: LECTERN_URL
          value: http://hh-rke-wp-webadmin-20-worker-1.caas.ebi.ac.uk:30200
        - name: DICTIONARY_VERSION
          value: '1.0'
        - name: DICTIONARY_NAME
          value: CancerModels_Dictionary
        - name: PORT
          value: '3009'
